# Reading data
Read the train.csv file as a pandas dataframe.

In [1]:
import pandas as pd
train = pd.read_csv("train.csv")
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Indexing
1. Create a function that returns the name of a passenger given their PassengerId.
2. Create a function that returns the PassengerId of a passenger given their Name.
3. Print a message with the ID of passenger **Montvila, Rev. Juozas** with the following format: 'The ID pf passenger Montvila, Rev. Juozas is ##'
4. Print a message with the name of the passenger with ID **42** with the following format: 'The passenger with ID 42 is X'

5. Print all information about the oldest passenger.

In [2]:
from funcionesTitanic import *

In [3]:
id_a_name(train, 62)

Name    Harris, Mr. Henry Birkhardt
Name: 62, dtype: object

In [4]:
nombre = 'Braund, Mr. Owen Harris'
id = name_to_id(train, nombre)
print(f"El ID del pasajero {nombre} es: {id}")

El ID del pasajero Braund, Mr. Owen Harris es: 0

In [5]:
name = "Montvila, Rev. Juozas"
id = name_a_id(train, name)
print(f"The ID of passenger {name} is {id}")

The ID of passenger Montvila, Rev. Juozas is 886

In [6]:
id = 0
name = id_a_name(train, id)  
print(f"The passenger with ID {id} is {name}")

The passenger with ID 0 is Name    Braund, Mr. Owen Harris
Name: 0, dtype: object

In [7]:
id_pasajero_mas_viejo = train.Age.idxmax()
print(train.loc[id_pasajero_mas_viejo])

PassengerId                                     631
Survived                                          1
Pclass                                            1
Name           Barkworth, Mr. Algernon Henry Wilson
Sex                                            male
Age                                            80.0
SibSp                                             0
Parch                                             0
Ticket                                        27042
Fare                                           30.0
Cabin                                           A23
Embarked                                          S
Name: 630, dtype: object

In [8]:
train[train.PassengerId==1].Name
def id_to_name(df: pd.DataFrame, id: int)-> str:
    """Regresa el nombre del pasajero dado su ID

    Args:
        df (pd.DataFrame): Conjunto de datos
        id (int): id del pasajero 

    Returns:
        str: El nombre del pasajero 
    """
    return "Montvila, Rev. Juozas"
id_to_name(train, 100)

'Montvila, Rev. Juozas'

In [9]:
passenger = train[train.PassengerId==1].Name
passenger.values[0]

'Braund, Mr. Owen Harris'

In [19]:
train = pd.read_csv("train.csv")
train = train.set_index("PassengerId")
train

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [12]:
train.iloc[[1,5,9]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

# Subseting
We are asked to share data for analysis by a third party. Since our dataset contains personal details, we only want to share with them the following information: ticket classes, fares and port of embarkation. We are asked to deliver a sample of the first 100 rows of this dataset.

6. Create and save the new dataset in **data/port_fares.csv**.

In [13]:
subset = train.iloc[:100]
subset = subset.loc[:, ['Pclass', 'Fare', 'Embarked']]
subset.to_csv('data/port_fares.csv', index=False)
subset.head()

   Pclass     Fare Embarked
0       3   7.2500        S
1       1  71.2833        C
2       3   7.9250        S
3       1  53.1000        S
4       3   8.0500        S

# Counting
7. We want to know if there were any survivors over the age of 60, print all of their information.
8. How many people over 60 survived?
9. What percentage of people over 60 survived?

In [14]:
#7
supervi_mayores_60 = train[(train.Age > 60) & (train.Survived == 1)]
print(supervi_mayores_60)
#8
cantidad_supervi = supervi_mayores_60.shape[0]

print(f"Había {cantidad_supervi} supervivientes mayores de 60 años.")

#9
total_60 = train[train.Age > 60].shape[0]
supervi_mayores_60 = supervi_mayores_60.shape[0]
porcentaje_supervi = (supervi_mayores_60 / total_60) * 100 if total_60 > 0 else 0
print(f"\nEl porcentaje de supervivientes mayores de 60 años es {porcentaje_supervi:.2f}%")

     PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia
483          484         1       3                     Turkula, Mrs. (Hedwig)
570          571         1       2                         Harris, Mr. George
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)

        Sex   Age  SibSp  Parch       Ticket     Fare Cabin Embarked
275  female  63.0      1      0        13502  77.9583    D7        S
483  female  63.0      0      0         4134   9.5875   NaN        S
570    male  62.0      0      0  S.W./PP 752  10.5000   NaN        S
630    male  80.0      0      0        27042  30.0000   A23        S
829  female  62.0      0      0       113572  80.0000   B28      NaN
Había 5 supervivientes mayores de 60 años.

El porcentaje de supervivientes mayores de 60 años es 22.73%

# Women and children first?
10. Find out if women and children were more likely to survive.

In [15]:
women_Child = (train['Sex'] == 'female') & (train["Age"]<18)
superv_WyC = train[women_Child].Survived.mean()
print(f'La tasa de supervivencia entre mujeres y niños es de: {superv_WyC:.2%}')

La tasa de supervivencia entre mujeres y niños es de: 69.09%

11. Write a function that returns the percentage of people that survived from a subset given as a boolean Pandas series.

In [16]:
def surv_percentage(subset):
    return subset['Survived'].mean() * 100

high_fare = train[train['Fare'] > 50]

high_fare = surv_percentage(high_fare)


print(f'El porcentaje de supervivencia relacionado a los pasajeros con tarifa alta es de: {high_fare:.2f}%')

El porcentaje de supervivencia relacionado a los pasajeros con tarifa alta es de: 68.12%

# Summarizing

12. What is the median age of the passengers?
13. How many passengers embarked from each port?

In [17]:
#12
median_age = train.Age.mean()
print(f'La edad media de los pasajeros en el titanic es de: {median_age}')

#13
type_port = train.Embarked.value_counts()
print(f'El número de pasajeros en cada embarque son: {type_port}')

La edad media de los pasajeros en el titanic es de: 29.69911764705882
El número de pasajeros en cada embarque son: Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

14. Generate two hypotheses about how does the survival rate differ among groups of passengers. Write your code to explore both hypotheses.

In [18]:
#14 
#Hipótesis 1. El puerto S representaba una mayor probabilidad de supervivencia

port_S_pass = train[train['Embarked'] == 'S']
port_S_surv_rate = port_S_pass['Survived'].mean() * 100
print(f'Tasa de supervivencia de los pasajeros del puerto S: {port_S_surv_rate:.2f}%')

port_C_pass = train[train['Embarked'] == 'C']
port_C_surv_rate = port_C_pass['Survived'].mean() * 100
print(f'Tasa de supervivencia de los pasajeros del puerto C: {port_C_surv_rate:.2f}%')

port_Q_pass = train[train['Embarked'] == 'Q']
port_Q_surv_rate = port_Q_pass['Survived'].mean() * 100
print(f'Tasa de supervivencia de los pasajeros del puerto Q: {port_Q_surv_rate:.2f}%')

print(f'La hipotesis es erronea, ya que el embarcadero con mayor probabildiad de supervivecia fue: C')


#Hipotesis 2. Viajar solo en tercera clase tiene mayor tasa de supervivencia que viajar en grupo
train['Solo'] = (train['SibSp'] == 0) & (train['Parch'] == 0)

third_class_pass = train[train['Pclass'] == 3]

solo_p = third_class_pass[third_class_pass['Solo'] == True]

group_p = third_class_pass[third_class_pass['Solo'] == False]

solo_rate = solo_p['Survived'].mean() * 100

group_rate = group_p['Survived'].mean() * 100

print(f'Tasa de supervivencia de los pasajeros de tercera clase que viajaban solos: {solo_rate:.2f}%')
print(f'Tasa de supervivencia de los pasajeros de tercera clase que viajaban en grupo: {group_rate:.2f}%')

print(f'La hipotesis es erronea, ya que los pasajeros con mayor probabildiad de supervivecia fueron: Los que viajaban en grupo')

Tasa de supervivencia de los pasajeros del puerto S: 33.70%
Tasa de supervivencia de los pasajeros del puerto C: 55.36%
Tasa de supervivencia de los pasajeros del puerto Q: 38.96%
La hipotesis es erronea, ya que el embarcadero con mayor probabildiad de supervivecia fue: C
Tasa de supervivencia de los pasajeros de tercera clase que viajaban solos: 21.30%
Tasa de supervivencia de los pasajeros de tercera clase que viajaban en grupo: 29.94%
La hipotesis es erronea, ya que los pasajeros con mayor probabildiad de supervivecia fueron: Los que viajaban en grupo

In [20]:
import numpy as np

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
import time

start = time.time()

total = 0
for i in np.arange(10000000):
    total = i + total
print(total)
end = time.time()
print(end - start)

49999995000000
2.0152981281280518

In [22]:
start = time.time()

print(np.sum(np.arange(10000000)))

end = time.time()
print(end - start)

49999995000000
0.06028437614440918