# Reading data
Read the train.csv file as a pandas dataframe.

In [4]:
import pandas as pd
train = pd.read_csv("train.csv")
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Indexing
1. Create a function that returns the name of a passenger given their PassengerId.
2. Create a function that returns the PassengerId of a passenger given their Name.
3. Print a message with the ID of passenger **Montvila, Rev. Juozas** with the following format: 'The ID pf passenger Montvila, Rev. Juozas is ##'
4. Print a message with the name of the passenger with ID **42** with the following format: 'The passenger with ID 42 is X'

5. Print all information about the oldest passenger.

In [5]:
from funcionesTitanic import *

In [6]:
id_a_name(train, 62)

Name    Harris, Mr. Henry Birkhardt
Name: 62, dtype: object

In [8]:
name = "Braund, Mr. Owen Harris"
id = name_a_id(train, name)
print(f"The ID of passenger {name} is {id}")

The ID of passenger Braund, Mr. Owen Harris is 0

In [11]:
id = 0
name = id_a_name(train, id).values[0][0]  
print(f"The passenger with ID {id} is {name}")

The passenger with ID 0 is B

In [13]:
id_pasajero_mas_viejo = train['Age'].idxmax()
print(train.loc[id_pasajero_mas_viejo])

PassengerId                                     631
Survived                                          1
Pclass                                            1
Name           Barkworth, Mr. Algernon Henry Wilson
Sex                                            male
Age                                            80.0
SibSp                                             0
Parch                                             0
Ticket                                        27042
Fare                                           30.0
Cabin                                           A23
Embarked                                          S
Name: 630, dtype: object

In [12]:
train[train.PassengerId==1].Name
def id_to_name(df: pd.DataFrame, id: int)-> str:
    """Regresa el nombre del pasajero dado su ID

    Args:
        df (pd.DataFrame): Conjunto de datos
        id (int): id del pasajero 

    Returns:
        str: El nombre del pasajero 
    """
    return "Montvila, Rev. Juozas"
id_to_name(train, 100)

'Montvila, Rev. Juozas'

In [ ]:
passenger = train[train.PassengerId==1].Name
passenger.values[0]

In [ ]:
titanic = pd.read_csv("data/train.csv")
titanic = titanic.set_index('PassengerId')
titanic

In [14]:
train.iloc[[1,5,9]]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

# Subseting
We are asked to share data for analysis by a third party. Since our dataset contains personal details, we only want to share with them the following information: ticket classes, fares and port of embarkation. We are asked to deliver a sample of the first 100 rows of this dataset.

6. Create and save the new dataset in **data/port_fares.csv**.

In [ ]:
subset = titanic.iloc[.100]
subset = subset.loc[:, ['Pclass', 'Fare', 'Embarked']]
subset.to_csv('data/port_fares.csv', index=False)

# Counting
7. We want to know if there were any survivors over the age of 60, print all of their information.
8. How many people over 60 survived?
9. What percentage of people over 60 survived?

In [9]:
#7
supervi_mayores_60 = train[(train['Age'] > 60) & (train['Survived'] == 1)]
print(supervi_mayores_60)
#8
cantidad_supervi = supervi_mayores_60.shape[0]

print(f"Había {cantidad_supervi} supervivientes mayores de 60 años.")

#9
total_60 = train[train['Age'] > 60].shape[0]
supervi_mayores_60 = supervi_mayores_60.shape[0]
porcentaje_supervi = (supervi_mayores_60 / total_60) * 100 if total_60 > 0 else 0
print(f"\nEl porcentaje de supervivientes mayores de 60 años es {porcentaje_supervi:.2f}%")

             Survived  Pclass                                       Name  \
PassengerId
276                 1       1          Andrews, Miss. Kornelia Theodosia
484                 1       3                     Turkula, Mrs. (Hedwig)
571                 1       2                         Harris, Mr. George
631                 1       1       Barkworth, Mr. Algernon Henry Wilson
830                 1       1  Stone, Mrs. George Nelson (Martha Evelyn)

                Sex   Age  SibSp  Parch       Ticket     Fare Cabin Embarked
PassengerId
276          female  63.0      1      0        13502  77.9583    D7        S
484          female  63.0      0      0         4134   9.5875   NaN        S
571            male  62.0      0      0  S.W./PP 752  10.5000   NaN        S
631            male  80.0      0      0        27042  30.0000   A23        S
830          female  62.0      0      0       113572  80.0000   B28      NaN
Había 5 supervivientes mayores de 60 años.

El porcentaje de supervivientes mayores de 60 años es 22.73%

# Women and children first?
10. Find out if women and children were more likely to survive.

11. Write a function that returns the percentage of people that survived from a subset given as a boolean Pandas series.

# Summarizing

12. What is the median age of the passengers?
13. How many passengers embarked from each port?

14. Generate two hypotheses about how does the survival rate differ among groups of passengers. Write your code to explore both hypotheses.

In [1]:
import numpy as np

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
import time

start = time.time()

total = 0
for i in np.arange(10000000):
    total = i + total
print(total)
end = time.time()
print(end - start)

49999995000000
7.6209306716918945

In [5]:
start = time.time()

print(np.sum(np.arange(10000000)))

end = time.time()
print(end - start)

49999995000000
0.475353479385376