# Reading data
Read the train.csv file as a pandas dataframe.

In [33]:
import pandas as pd
titanic = pd.read_csv("data/train.csv") 
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Indexing
1. Create a function that returns the name of a passenger given their PassengerId.
2. Create a function that returns the PassengerId of a passenger given their Name.
3. Print a message with the ID of passenger **Montvila, Rev. Juozas** with the following format: 'The ID pf passenger Montvila, Rev. Juozas is ##'
4. Print a message with the name of the passenger with ID **42** with the following format: 'The passenger with ID 42 is X'

In [32]:
from titanic import*
id_to_name(titanic, 2)

AttributeError: module 'titanic' has no attribute 'PassengerId'

In [29]:
passenger = titanic[titanic.PassengerId == 1].Name
passenger[0]

AttributeError: module 'titanic' has no attribute 'PassengerId'

In [21]:
titanic.iloc[:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [23]:
def id_to_name(df:pd.DataFrame,id: int) -> str:
    passenger_name = df[df.PassengerId == id].Name
    return passenger_name[id-1]

print(id_to_name(titanic, 6))

Moran, Mr. James

In [24]:
def name_to_id(df:pd.DataFrame,name: str)-> int:
    passenger_id = df[df.Name == name].PassengerId
    return passenger_id.iloc[0]

In [25]:
def messages_id(df:pd.DataFrame, name: str)-> int:
    passenger_id = df[df.Name == name].PassengerId
    return print(f"The ID pf passenger of {name} is: {passenger_id.iloc[0]}")
messages_id(titanic, "Montvila, Rev. Juozas")

The ID pf passenger of Montvila, Rev. Juozas is: 887

In [26]:
def messages_name(df:pd.DataFrame, id:int)-> str:
    passenger_name = df[df.PassengerId == id].Name
    return print(f"'The passenger with ID {id} is {passenger_name[id-1]}")
messages_name(titanic, 42)

'The passenger with ID 42 is Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)

In [27]:
def print_info(df:pd.DataFrame)->pd.DataFrame:
    passenger_info = df[df.Age == df.Age.max()]
    return print(passenger_info)
print_info(titanic)

     PassengerId  Survived  Pclass                                  Name  \
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson

      Sex   Age  SibSp  Parch Ticket  Fare Cabin Embarked
630  male  80.0      0      0  27042  30.0   A23        S

5. Print all information about the oldest passenger.

# Subseting
We are asked to share data for analysis by a third party. Since our dataset contains personal details, we only want to share with them the following information: ticket classes, fares and port of embarkation. We are asked to deliver a sample of the first 100 rows of this dataset.

6. Create and save the new dataset in **data/port_fares.csv**.

In [22]:
port_fares = titanic.loc[:99, ['Pclass', 'Fare', 'Embarked']]
port_fares = port_fares.rename(columns = {"Pclass": "Ticket_classes", "Fare":"Fares", "Embarked": "Port_embarkation"})
port_fares.to_csv('data/port_fares.csv', index = False)
print(port_fares)

Moran, Mr. James

# Counting
7. We want to know if there were any survivors over the age of 60, print all of their information.
8. How many people over 60 survived?
9. What percentage of people over 60 survived?

In [2]:
df_survivors_over60 = titanic[(titanic.Age > 60) & (titanic.Survived == 1)]
print(df_survivors_over60)  
survivor_over60 = len(df_survivors_over60)
people_over60 = len(titanic[titanic.Age> 60])
percentage_survivors_over60 = (survivor_over60 / people_over60) * 100 #del total de personas arriba de 60
print(f"Porcentaje de sobrevivientes mayores de 60 años: {percentage_survivors_over60:.2f}%")
titanic.Survived.value_counts # Resumen
titanic.groupby("Survived")["Age"].mean() # Agrupar por supervivientes, seleccionar la edad y ver el promedio
# median(), max()
titanic.groupby(["Survived", "Sex"])["Age"].median() #Estadísticas

#Ejercicio
tabla = titanic.groupby([titanic["Age"] > 60, "Survived"]).size().reset_index(name="Count")
tabla_pivot = tabla.pivot(index="Age", columns="Survived", values="Count").fillna(0)
tabla_pivot.columns = [ "Survived"]
tabla_pivot.index.name = "Age > 60"
print(tabla_pivot)

     PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia
483          484         1       3                     Turkula, Mrs. (Hedwig)
570          571         1       2                         Harris, Mr. George
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)

        Sex   Age  SibSp  Parch       Ticket     Fare Cabin Embarked
275  female  63.0      1      0        13502  77.9583    D7        S
483  female  63.0      0      0         4134   9.5875   NaN        S
570    male  62.0      0      0  S.W./PP 752  10.5000   NaN        S
630    male  80.0      0      0        27042  30.0000   A23        S
829  female  62.0      0      0       113572  80.0000   B28      NaN
Porcentaje de sobrevivientes mayores de 60 años: 22.73%

ValueError: Length mismatch: Expected axis has 2 elements, new values have 1 elements

In [31]:
len(survivors_over_60)

5

In [32]:
over_60 = titanic[titanic.Age > 60]
len(survivors_over_60) / len(titanic)

0.005611672278338945

In [33]:
sum((titanic.Age > 60) & (titanic.Survived == 1))

5

In [34]:
over_60 = titanic[titanic.Age > 60]
len(survivors_over_60) / len(over_60)

0.22727272727272727

In [36]:
titanic.groupby('Survived')['Age'].median()

Survived
0    28.0
1    28.0
Name: Age, dtype: float64

# Women and children first?
10. Find out if women and children were more likely to survive.

11. Write a function that returns the percentage of people that survived from a subset given as a boolean Pandas series.

# Summarizing

12. What is the median age of the passengers?
13. How many passengers embarked from each port?

14. Generate two hypotheses about how does the survival rate differ among groups of passengers. Write your code to explore both hypotheses.

In [28]:
import time
import numpy as np

start = time.time()

total = 0
for i in np.arange(10000000):
    total = i + total

print(total)

end = time.time()
print(end - start)

49999995000000
6.079859495162964

In [29]:
import time
import numpy as np

start = time.time()

print(np.sum(np.arange(10000000)))

end = time.time()
print(end - start)

49999995000000
0.06600642204284668